version: '3.9'
services:
  tensorflow:
    build:
      context: ./.devcontainer
    image: ${USER}/${PROJECT_NAME}

    volumes:
      - type: bind
        source: .
        target: /workspaces/${PROJECT_NAME}
    working_dir: /workspaces/${PROJECT_NAME}
    command: python download_Inter4k_Dataset.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - CUDA_VISIBLE_DEVICES
